import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeScript from "@/lib/themeScript";
import "./page.css";
import "@/assets/scss/index.scss";
import "@/assets/scss/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ThemeScript />
        {children}
        <Footer />
      </body>
    </html>
  );
}
