export const extraPlugins =
  "save,pastefromword,templates,language,codesnippet,div,showblocks,copyformatting,basicstyles,clipboard,format,justify,colorbutton,font,print,preview,find,flash,forms,iframe,smiley,pagebreak,stylescombo,save ,newpage,selectall,exportpdf,justify,bidi";
export const toolBarConfiguration = [
  {
    name: "document",
    items: [
      "Source",
      "-",
      "Save",
      "NewPage",
      "ExportPdf",
      "Preview",
      "Print",
      "-",
      "Templates",
    ],
  },
  {
    name: "clipboard",
    items: [
      "Cut",
      "Copy",
      "Paste",
      "PasteText",
      "PasteFromWord",
      "-",
      "Undo",
      "Redo",
    ],
  },

  {
    name: "editing",
    items: ["Find", "Replace", "-", "SelectAll", "-", "Scayt"],
  },
  {
    name: "selection",
    item: ["SelectAll"],
  },
  {
    name: "forms",
    items: [
      "Form",
      "Checkbox",
      "Radio",
      "TextField",
      "Textarea",
      "Select",
      "Button",
      "ImageButton",
      "HiddenField",
    ],
  },
  "/",
  {
    name: "basicstyles",
    groups: ["basicstyles", "cleanup"],
    items: [
      "Bold",
      "Italic",
      "Underline",
      "Strike",
      "Subscript",
      "Superscript",
      "-",
      "CopyFormatting",
      "RemoveFormat",
    ],
  },
  {
    name: "paragraph",
    items: [
      "NumberedList",
      "heading",
      "BulletedList",
      "-",
      "Outdent",
      "Indent",
      "-",
      "Blockquote",
      "CreateDiv",
      "-",
      "JustifyLeft",
      "JustifyCenter",
      "JustifyRight",
      "JustifyBlock",
      "-",
      "BidiLtr",
      "BidiRtl",
      "Language",
    ],
  },
  { name: "links", items: ["Link", "Unlink", "Anchor"] },
  {
    name: "insert",
    items: [
      "Image",
      "CodeSnippet",
      "Table",
      "HorizontalRule",
      "Smiley",
      "SpecialChar",
      "PageBreak",
      "Iframe",
    ],
  },
  "/",
  {
    name: "styles",
    items: ["Styles", "Format", "Font", "FontSize"],
  },
  { name: "colors", items: ["TextColor", "BGColor"] },
  { name: "tools", items: ["Maximize", "ShowBlocks"] },
  { name: "others" },
  { name: "about", items: ["About"] },
];
